[Addon]
Name=Pipe to Type
Comment=Simulate text input by writing to $XDG_RUNTIME_DIR/fcitx5-pipe-to-type
Category=Module
Version=1.0.1
Type=SharedLibrary
Library=fcitx5-pipe-to-type
OnDemand=False
Configurable=False
